### ISSUE TITLE
Issue a stable release

### ISSUE THREAD

**Issue by SilverFire** [rosstuck/sort#6]
Hello. Could you, please, bump a release?

**Comment by rosstuck** [comment]
Hi! I don't actually know if the library is stable at this point, it was more of a personal playground project and I didn't think anyone would ever actually use it.

If it's something you'd actually like, I can try to dust it off in the coming week and see if I can remember what the status of it all is.

Either day, thanks for being interested in it :sweat_smile:

**Comment by SilverFire** [comment]
> I didn't think anyone would ever actually use it

Well... Your library is well-documented, has tests, 22 stars and nobody blames you in issues for something not working :) Based on these points, I think it is pretty stable to be released.

Actually, I can continue using it requiring it as `dev-master`, but you've done a good job and your lib deserves to be released.

**Comment by rosstuck** [comment]
Okay, dusted it off and updated it for PHP7. Probably won't support it much (read: at all :grin: ) going forward but hopefully that makes it a little safer to include. Thanks for using it!
