### ISSUE TITLE
Why only versión 7?

### ISSUE THREAD

**Issue by Oxicode** [rosstuck/sort#8]
https://github.com/rosstuck/sort/blob/bf255ff4f1a6d84dcebfb9cb8bad795d798293e1/composer.json#L13

**Comment by rosstuck** [comment]
Good question! I usually only support versions of PHP that are actively maintained by PHP itself. It lets me evolve libraries and gives a gentle nudge to folks that they need to upgrade for security patches.

With this lib specifically, I'll probably add strict types soon and the iterable typehint from 7.1 would make a lot of sense, so might even bump it to that.

Hope that answers your question. :smile:
